### ISSUE TITLE
Let users filter the data

### ISSUE THREAD

**Issue by pchhibber** [treestrokes/today-we-lack#7]
- ~~Filter by date range (2 dropdowns for from and to date)~~ [cancelling for now]
- [x] Filter by year
- [x] Filter by location (dropdown or multi-select for city)

**Comment by VijayKrishna** [comment]
Ref. #8 ... might want a integration between issues #7 and #8.

**Comment by VijayKrishna** [comment]
should we consider moving the date-range todo in this issue as its own separate issue? One reason why i like the year-based filtering is the volume that a single year brings with it.

**Comment by pchhibber** [comment]
agree with the volume bit, but i don't see too much of a value add by providing a date range filter right now. limiting it to filtering by year (as it is currently implemented) has a certain simplicity which i feel is adequate at this stage.

**Comment by pchhibber** [comment]
Am removing the 'filter by category' to do from this issue, and adding in #8 that we need to have categories.
